FROM debian:stable-slim

COPY . ./shbaam
WORKDIR /shbaam

RUN apt-get update && \
    apt-get install -y --no-install-recommends python libspatialindex-c4v5 && \
    rm -rf /var/lib/apt/lists/*

ADD https://bootstrap.pypa.io/get-pip.py .
RUN python get-pip.py --no-cache-dir && \
    rm get-pip.py

RUN pip install Fiona netCDF4==1.3.1 numpy Rtree Shapely --no-cache-dir
